Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f4418a61bf8>
Traceback (most recent call last):
  File "/home/rossil1/CS1XA3/pythonEnv/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/rossil1/CS1XA3/pythonEnv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/home/rossil1/CS1XA3/pythonEnv/lib/python3.6/site-packages/django/core/management/base.py", line 425, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
?: (urls.E006) The STATIC_URL setting must end with a slash.

System check identified 1 issue (0 silenced).
Performing system checks...

Performing system checks...

System check identified no issues (0 silenced).

You have 15 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
April 04, 2019 - 16:02:56
Django version 2.1.7, using settings 'django_project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
